### PR TITLE
[567287] move rotativeImage to kitalpha core

### PR DESCRIPTION
**Pull request by tguiu**
includes Capella changes

### CODE REVIEW

**Review by pdulth — CHANGES_REQUESTED** [review]
Some comments:

1: 
https://github.com/eclipse/kitalpha/blob/f84002ac13419d2fc247308605e13fa15fc60b47/common/plugins/org.polarsys.kitalpha.common.sirius.extension.rotativeimage/src/org/polarsys/kitalpha/common/sirius/extension/rotativeimage/RotativeImageEditPartProvider.java#L29

In this method, several different edit parts are replaced by RotativeImageEditPart (label of ports will also be replaced by a rotative image) 

In https://github.com/eclipse/capella/blob/master/core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/editpart/RotativeImageEditPartProvider.java#L63-L72
the WorkspaceImageEditPart.VISUAL_ID is replaced by RotativeImageEditPart, 
the DNode4EditPart.VISUAL_ID is replaced by RotativeDNode4EditPart
RotativeImageEditPart and RotativeDNode4EditPart doesn"t have same inheritancy.

2:
https://github.com/eclipse/kitalpha/blob/f84002ac13419d2fc247308605e13fa15fc60b47/common/plugins/org.polarsys.kitalpha.common.sirius.extension.rotativeimage/src/org/polarsys/kitalpha/common/sirius/extension/rotativeimage/RotativeImageEditPart.java#L104
please avoid direct cast like:
https://github.com/eclipse/capella/blob/master/core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/editpart/RotativeImageEditPart.java#L60


3: 
Layout policy are the same than parent class
https://github.com/eclipse/kitalpha/blob/f84002ac13419d2fc247308605e13fa15fc60b47/common/plugins/org.polarsys.kitalpha.common.sirius.extension.rotativeimage/src/org/polarsys/kitalpha/common/sirius/extension/rotativeimage/RotativeImageEditPart.java#L78

(there is no more policy in https://github.com/eclipse/capella/blob/master/core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/editpart/RotativeImageEditPart.java#L39)

4:
For RotativeWorkspaceImageFigure
Can you inspire from :
https://github.com/eclipse/capella/blob/master/core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/editpart/RotativeWorkspaceImageFigure.java
https://github.com/eclipse/capella/blob/master/core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/editpart/RotativeWorkspaceImageHelper.java

the old version of refreshFigure use flyWeightImage which has bad performance, the new one use Sirius Image Registry to avoid reloading the image.

Thanks

**Comment by tguiu** [comment]
> 1:
> the WorkspaceImageEditPart.VISUAL_ID is replaced by RotativeImageEditPart,
> the DNode4EditPart.VISUAL_ID is replaced by RotativeDNode4EditPart
> RotativeImageEditPart and RotativeDNode4EditPart doesn"t have same inheritancy.
> 

I put these changes although they may be seen as Capella integration task.
I didn't catch the usage of XXX.VISUAL_ID tests.

> 2:
> https://github.com/eclipse/kitalpha/blob/f84002ac13419d2fc247308605e13fa15fc60b47/common/plugins/org.polarsys.kitalpha.common.sirius.extension.rotativeimage/src/org/polarsys/kitalpha/common/sirius/extension/rotativeimage/RotativeImageEditPart.java#L104
> 
I added the check although it's surely useless. If the type is not as expected, will there be a figure object at the end ?

**Comment by pdulth** [comment]
> 
> 
> > 1:
> > the WorkspaceImageEditPart.VISUAL_ID is replaced by RotativeImageEditPart,
> > the DNode4EditPart.VISUAL_ID is replaced by RotativeDNode4EditPart
> > RotativeImageEditPart and RotativeDNode4EditPart doesn"t have same inheritancy.
> 
> I put these changes although they may be seen as Capella integration task.
> I didn't catch the usage of XXX.VISUAL_ID tests.
> 
> > 2:
> > https://github.com/eclipse/kitalpha/blob/f84002ac13419d2fc247308605e13fa15fc60b47/common/plugins/org.polarsys.kitalpha.common.sirius.extension.rotativeimage/src/org/polarsys/kitalpha/common/sirius/extension/rotativeimage/RotativeImageEditPart.java#L104
> 
> I added the check although it's surely useless. If the type is not as expected, will there be a figure object at the end ?

idk, with sirius its never useless :)

**Comment by pdulth** [comment]
> 
> 
> > 1:
> > the WorkspaceImageEditPart.VISUAL_ID is replaced by RotativeImageEditPart,
> > the DNode4EditPart.VISUAL_ID is replaced by RotativeDNode4EditPart
> > RotativeImageEditPart and RotativeDNode4EditPart doesn"t have same inheritancy.
> 
> I put these changes although they may be seen as Capella integration task.
> I didn't catch the usage of XXX.VISUAL_ID tests.
> 
A graphical element is compound by several edit parts,
for instance, on a function, there will be one for label, one for the shadow, one for the box, etc, etc. all of these edit parts have the same semanticElement.
In ports, there might have the WorkspaceImageEditPart, but also the DNode4EditPart (the label on ports i think). and maybe others, idk. If we replace all of these by our RotativeImageEditPart, it seems to work, but there is some cast at some point in some sirius versions.
if we dont create a RotativeDNode4EditPart, then GMF will fail at some point. (code is older than 2014 so we dont have git history for this class though)

**Review by bzendagui — APPROVED** [review]

**Pull request merged**
